"""Add freelancer_id to tasks table

Revision ID: 3f11cf197f96
Revises: ae69ebb6a20c
Create Date: 2025-10-25 07:36:12.702512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f11cf197f96'
down_revision = 'ae69ebb6a20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freelancer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_freelancer_id_freelancers'), 'freelancers', ['freelancer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_freelancer_id_freelancers'), type_='foreignkey')
        batch_op.drop_column('freelancer_id')

    # ### end Alembic commands ###
