"""Add created_at attribute tp Client

Revision ID: 4f4c1bd879ef
Revises: 6d1ef967796f
Create Date: 2025-10-30 12:09:40.111615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4c1bd879ef'
down_revision = '6d1ef967796f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
