"""add file_url to Milestone model and delete the Deliverable model

Revision ID: 82b73630e46b
Revises: f69a29d462fd
Create Date: 2025-10-21 17:00:26.134896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b73630e46b'
down_revision = 'f69a29d462fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliverables')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    op.create_table('deliverables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contract_id', sa.INTEGER(), nullable=True),
    sa.Column('uploader_id', sa.INTEGER(), nullable=True),
    sa.Column('file_url', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='fk_deliverables_contract_id_contracts'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
