"""Add freelancer_id to payments

Revision ID: ae69ebb6a20c
Revises: 82b73630e46b
Create Date: 2025-10-25 00:58:40.442836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae69ebb6a20c'
down_revision = '82b73630e46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freelancer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_freelancer_id_freelancers'), 'freelancers', ['freelancer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_freelancer_id_freelancers'), type_='foreignkey')
        batch_op.drop_column('freelancer_id')

    # ### end Alembic commands ###
