"""Remove cover_letterattribute in Application model and add cover_letter_file attribute

Revision ID: b0a379d01c43
Revises: 82b73630e46b
Create Date: 2025-10-25 22:19:31.769702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a379d01c43'
down_revision = '82b73630e46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter_file', sa.String(length=255), nullable=True))
        batch_op.drop_column('cover_letter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter', sa.TEXT(), nullable=True))
        batch_op.drop_column('cover_letter_file')

    # ### end Alembic commands ###
