"""Remove skills from Frelancer and required skill from task

Revision ID: f826aeec8768
Revises: a711a2523ef5
Create Date: 2025-10-21 15:53:20.400852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f826aeec8768'
down_revision = 'a711a2523ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancers', schema=None) as batch_op:
        batch_op.drop_column('skills')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('required_skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.TEXT(), nullable=True))

    with op.batch_alter_table('freelancers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
